REQUIRED_COLUMNS = [
    "ORDER_ID", "ORDER_DATE", "ORDERSTATE", "ORDERTYPE",
    "AMOUNT", "SKU_ID", "BRAND", "CATEGORY",
    "OUTLET_ID", "OUTLET_NAME", "CITY", "ZONE", "STATE",
    "USER_ID", "USERNAME", "DESIGNATION",
    "DISCOUNT_AMOUNT", "TIME_SPENT_AT_OUTLET"
]
